### ISSUE TITLE
Commit for BYOD 1.0.1 is detached

### ISSUE THREAD

**Issue by hfiguiere** [Chowdhury-DSP/chowdsp_juce_dsp#1]
Commit 0e8f18b4be33bdf38e07dd537a22e85d764ec4a4 as needed for BYOD 1.0.1 (submodules) is detached, which mean in some situations it is not fetched by git. Also it could be just garbage collected.

Solution: Please create a branch or tag for commit 0e8f18b4be33bdf38e07dd537a22e85d764ec4a4

**Comment by hfiguiere** [comment]
![image](https://user-images.githubusercontent.com/114441/188936418-6da9d513-9a08-4748-b692-6ddf5a073a8b.png)

**Comment by jatinchowdhury18** [comment]
Oh, thanks for the head's up! I've moved that commit to the new `juce-6.1.3` branch for now. I'll think a bit more about a better strategy to use for future JUCE updates moving forward.

**Comment by hfiguiere** [comment]
This works great. Thank you!
